//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainFuck.TestRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainFuck.TestRunner.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +++[&gt;+++++&lt;-]&gt;&gt;+&lt;[&gt;&gt;++++&gt;++&gt;+++++&gt;+++++&gt;+&gt;&gt;+&lt;++[++&lt;]&gt;---]
        ///
        ///&gt;++++.&gt;&gt;&gt;.+++++.&gt;------.&lt;--.+++++++++.&gt;+.+.&lt;&lt;&lt;&lt;---.[&gt;]&lt;&lt;.&lt;&lt;&lt;.-------.&gt;++++.
        ///&lt;+++++.+.&gt;-----.&gt;+.&lt;++++.&gt;&gt;++.&gt;-----.
        ///
        ///&lt;&lt;&lt;-----.+++++.-------.&lt;--.&lt;&lt;&lt;.&gt;&gt;&gt;.&lt;&lt;+.&gt;------.-..--.+++.-----&lt;++.&lt;--[&gt;+&lt;-]
        ///&gt;&gt;&gt;&gt;&gt;--.--.&lt;++++.&gt;&gt;-.&lt;&lt;&lt;.&gt;&gt;&gt;--.&gt;.
        ///
        ///&lt;&lt;&lt;&lt;-----.&gt;----.++++++++.----&lt;+.+++++++++&gt;&gt;--.+.++&lt;&lt;&lt;&lt;.[&gt;]&lt;.&gt;&gt;
        ///
        ///,[&gt;&gt;+++[&lt;+++++++&gt;-]&lt;[&lt;[-[-&lt;]]&gt;&gt;[&gt;]&lt;-]&lt;[&lt;+++++&gt;-[&lt;+++&gt;-[&lt;--&gt;-[&lt;+++&gt;-
        ///[&lt;++++[&gt;[-&gt;&gt;]&lt;[&gt;&gt;]&lt;&lt;-]&gt;[&lt;+++&gt;-[&lt;---&gt;-[&lt;++++&gt;-[&lt;+++[&gt;[-[-[-[-&gt;&gt;]]]]&lt;[&gt;&gt;]&lt;&lt;-]
        ///&gt;[&lt;+&gt;-[&lt;-&gt;-[&lt;++&gt;-[&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbf2c {
            get {
                return ResourceManager.GetString("dbf2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some little programs for testing brainfuck implementations.
        ///
        ///
        ///&gt;,&gt;+++++++++,&gt;+++++++++++[&lt;++++++&lt;++++++&lt;+&gt;&gt;&gt;-]&lt;&lt;.&gt;.&lt;&lt;-.&gt;.&gt;.&lt;&lt;.
        ///This is for testing i/o; give it a return followed by an EOF. (Try it both
        ///with file input--a file consisting only of one blank line--and with
        ///keyboard input, i.e. hit return and then ctrl-d (Unix) or ctrl-z
        ///(Windows).)
        ///It should give two lines of output; the two lines should be identical, and
        ///should be lined up one over the other. If that doesn&apos;t happen, ten is not
        ///coming t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tests {
            get {
                return ResourceManager.GetString("tests", resourceCulture);
            }
        }
    }
}
